networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nganx.conf'
    depends_on: 
      - backend
      - frontend
      - postgres
    networks: 
      - dev
  
  backend:
    build:
      context: ./server-nest-investigator
    environment:
      CLIENT_HOST: ${ENV_CLIENT_HOST}

      DB_HOST: ${ENV_DB_HOST}
      DB_PORT: ${ENV_DB_PORT}
      DB_USERNAME: ${PG_USERNAME} 
      DB_PASSWORD: ${PG_PASSWORD}
      DB_NAME: ${PG_DB}
      DB_SYNCHRONIZATION: ${ENV_DB_SYNCHRONIZATION}
      DB_LOGGING: ${ENV_DB_LOGGING}

      JWT_ACCESS_TOKEN_SECRET: ${ENV_JWT_ACCESS_TOKEN_SECRET} 
      JWT_ACCESS_TOKEN_EXPIRATION: ${ENV_JWT_ACCESS_TOKEN_EXPIRATION} 
      JWT_REFRESH_TOKEN_SECRET: ${ENV_JWT_REFRESH_TOKEN_SECRET} 
      JWT_REFRESH_TOKEN_EXPIRATION: ${ENV_JWT_REFRESH_TOKEN_EXPIRATION} 
    networks: 
      - dev

  frontend:
    build:
      context: ./client-vite-investigator
    environment:
      VITE_SERVER_URL: ${ENV_VITE_SERVER_URL}
    networks: 
      - dev

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USERNAME: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    networks: 
      - dev